version: '3.8'

services: 
    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        ports: 
            - "9000:9000"
        restart: unless-stopped
        volumes: 
            - ./backend-test/node_modules:/usr/app/node_modules
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"
        restart: unless-stopped
        environment: 
            CHOKIDAR_USEPOLLING: "true"
        volumes: 
            - ./node_modules:/usr/app/node_modules
            - .:/usr/app